version: "3"
services:
    jaeger:
        image: jaegertracing/all-in-one:1.22
        expose:
            - 14250
        ports:
            - 16686:16686

    zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    otel_collector:
        image: otel/opentelemetry-collector
        command: ["--config=/otel-collector-config.yaml"]
        expose:
            - 8889
        ports:
            - 55680:55680
        volumes:
            - ./otel-collector/otel-collector-config.yaml:/otel-collector-config.yaml

