version: "3"
services:
    jaeger:
        image: jaegertracing/all-in-one:1.22
        expose:
            - 14250
        ports:
            - 16686:16686

    zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411

    otel_collector:
        image: otel/opentelemetry-collector
        command: ["--config=/otel-collector-config.yaml"]
        ports:
            - 55680:55680
        volumes:
            - ./otel-collector/otel-collector-config.yaml:/otel-collector-config.yaml

