version: "3"
services:
    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    otel_collector:
        image: otel/opentelemetry-collector-contrib
        command:
            - "--config=/otel-collector-config.yaml"
            - "--mem-ballast-size-mib=683"
        expose:
            - 8889
        ports:
            - 55680:55680
        environment:
            - NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY
        volumes:
            - ./otel-collector/otel-collector-config.yaml:/otel-collector-config.yaml
        depends_on:
            - loki

    loki:
        image: grafana/loki:2.1.0
        command: "-config.file=/mnt/config/loki-config.yaml"
        expose:
            - 3100
        volumes:
            - ./loki:/mnt/config

    grafana:
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        volumes:
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
        depends_on:
            - loki
