receivers:
    otlp:
        protocols:
            grpc:

exporters:
    jaeger:
        endpoint: jaeger:14250
        insecure: true
    zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
        insecure: true
    prometheus:
        endpoint: 0.0.0.0:8889
        resource_to_telemetry_conversion:
            enabled: true

processors:
    batch:

extensions:
    health_check:
    pprof:
        endpoint: :1888
    zpages:
        endpoint: :55679

service:
    extensions: [pprof, zpages, health_check]
    pipelines:
        metrics:
            receivers:
                - otlp
            exporters:
                - prometheus

        traces:
            receivers:
                - otlp
            processors:
                - batch
            exporters:
                - jaeger
                - zipkin
